[package]
name = "shard"
version = "0.1.0"
edition = "2021"


[dependencies]
lib = { path = "../lib" }

anyhow = "*"
tracing = "*"
tracing-subscriber = { version = "*", features = ["parking_lot"] }
clap = { version = "*", features = ["derive"] }

tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"

once_cell = "*"

uuid = { version = "*", features = ["v4", "fast-rng"] }
redis = { version = "*", default-features = false, features = [
    "acl",
    "aio",
    "ahash",
    "tokio-comp",
] }
