[package]
name = "shard"
version = "0.1.0"
edition = "2021"


[dependencies]
lib = { path = "../lib" }

anyhow = "*"
tracing = "*"
tracing-subscriber = { version = "*", features = ["parking_lot"] }
config = "*"
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
axum = { version = "*", features = ["tracing"] }
reqwest = { version = "*", features = ["native-tls"] }
once_cell = "*"
uuid = { version = "*", features = ["v7", "fast-rng"] }
redis = { version = "*", default-features = false, features = [
    "acl",
    "aio",
    "ahash",
    "tokio-comp",
] }
chrono = "*"
