CREATE TABLE IF NOT EXISTS ids {
    order BIGSERIAL PRIMARY KEY,
    id UUID NOT NULL UNIQUE,
}

CREATE TABLE IF NOT EXISTS chunks
(
    hash UUID PRIMARY KEY,
    data BYTEA NOT NULL,
    stored TIMESTAMP WITH TIME ZONE NOT NULL,
    id UUID REFERENCES ids(id)
);